### ISSUE TITLE
Request: Flexibility for Frontend, Serverless, and Edge Runtimes

### ISSUE THREAD

**Issue by theshanergy** [themaximalist/llm.js#6]
Hello Maximalist,

Great package - I'm interested in using LLM.js for a project but currently I'm unable to do so due to its limitations around frontend compatibility. I'd like to suggest a couple of enhancements that would make it possible for developers to utilize this wrapper in a broader range of environments.

### Dependency Reduction
LLM.js relies on fs, node-fetch, and dotenv, which aren't always practical outside of Node.js environments. Could these be optional or removed to ease use in various contexts without extra bundling or polyfills?

### Custom Endpoint URLs
Allowing users to set their own endpoint URLs would be helpful for client-side and edge runtimes, by permitting requests to be proxied or alternative endpoints to be used.

 &nbsp;
Implementing these features would greatly enhance the library's usability for frontend projects and allow developers like me to leverage its capabilities in our work. I'm keen to hear your thoughts on these suggestions and am more than willing to contribute to the discussion or help with implementation.

Shane

**Comment by themaximalist** [comment]
Hey @theshanergy thanks for the feedback, I definitely think this is doable. It may take some work but I'll try to get this done in the next major update.

Also I've been using Model Deployer to handle proxying requests which works with LLM.js, see
* https://modeldeployer.com/
* https://modeldeployer.themaximalist.com/

And let me know if those would work for your case or you're looking for something else.

**Comment by theshanergy** [comment]
Thanks for the quick response @themaximalist 

re: modeldeployer - I had a look, but it seems to use a single model at a time - is that correct? ie. there is no way for me to switch model providers on the fly from my app, or pass user provided api keys?

**Comment by sudslab** [comment]
Would love to see support for specifying a custom port / url for use with `llamafile`. This would allow me to run multiple models via llamafile vs currently being restricted to a single model running on 8080.

**Comment by themaximalist** [comment]
@theshanergy passing an "apikey" option should work now, and I'll get multiple models supported. The original idea was to setup multiple API keys to restrict it, but will find a way to have the option

@sudslab this should be possible with the "endpoint" option, see https://github.com/themaximalist/llm.js/blob/main/src/llamafile.js#L37

**Comment by themaximalist** [comment]
This just got merged in at https://github.com/themaximalist/llm.js/pull/7

Browser support is still new, so please let me know if anything doesn't work as expected.
